### ISSUE TITLE
Instructions are Unclear

### ISSUE THREAD

**Issue by PieCreeper12** [threecreepio/smb-glitchedworlds#1]
I am trying to apply the patch to Super Mario Bros. However, I have no idea how to do that. All it says is "Then simply apply that IPS (using for instance Lunar IPS) to the original, unmodified version of the Super Mario Bros. (US/World) ROM." but it gives no instructions on how to do that with Lunar IPS. When I click apply, it shows the patch but does not let me select the game I am trying to apply the patch to.

**Comment by sciolist** [comment]
Sorry you're having issues, I'll see if I can come up with a better description. Can you try this:

https://www.pokemoncoders.com/lunar-ips-patcher-tutorial/

And in 'step 5' select an original Super Mario Bros. US rom. The guide mentions gameboy games, but the process is the same.

**Comment by natelbug** [comment]
Try using Floating IPS and click apply patch

**Comment by threecreepio** [comment]
Hey, sorry I never had a chance to look into this. I modified the instructions a little bit with a link to a page with a little clearer instructions.
