### ISSUE TITLE
When I apply the patch and load the ROM, the resulting game is unplayable

### ISSUE THREAD

**Issue by LiterallyLegendary** [threecreepio/smb-glitchedworlds#2]
Here is a picture of what happened:
![Screenshot 2020-10-13 at 10 47 27 PM](https://user-images.githubusercontent.com/72235715/100947051-9ea2de00-34b9-11eb-81d1-55a1a3c60fc3.png)

**Comment by threecreepio** [comment]
Hm it does definitely work here, haven't seen that happen.

What hardware (or emulator) are you using?

Can you go to http://onlinemd5.com/ and check the MD5 sums for the roms?
The resulting MD5 for the original SMB1 rom should be `811B027EAF99C2DEF7B933C5208636DE`
and the patched file should be `AB320FF71A3E57DAC0AA4055299FEC7A`

**Comment by LiterallyLegendary** [comment]
The checksums are AB320FF71A3E57DAC0AA4055299FEC7A and
811B027EAF99C2DEF7B933C5208636DE.
I was using Eclipse, which is an online emulator.

**Comment by threecreepio** [comment]
Yeah that emulator doesn't seem to be able to run the smb pellsson practise roms either, so it seems that emulator is not accurately reproducing the behavior of a real NES. You can try the rom here: https://tsone.kapsi.fi/em-fceux/ where it does work, but without looking into what Eclipse is doing wrong I'm afraid I won't be able to work around the issue. :(

**Comment by LiterallyLegendary** [comment]
> Yeah that emulator doesn't seem to be able to run the smb pellsson practise roms either, so it seems that emulator is not accurately reproducing the behavior of a real NES. You can try the rom here: https://tsone.kapsi.fi/em-fceux/ where it does work, but without looking into what Eclipse is doing wrong I'm afraid I won't be able to work around the issue. :(

Thanks so much! This hack is super fun to play. I want to see how many of the 65536 levels I can beat.

**Comment by LiterallyLegendary** [comment]
Is there any way I could use game genie codes on the emulator website that you mentioned?

**Comment by threecreepio** [comment]
Oh sorry I never answered this, I tried to check if you could use game genie codes with it somehow but didn't see anything. Hope it worked out for you. :)
