### ISSUE TITLE
Additional START button actions.

### ISSUE THREAD

**Issue by yum13241** [threecreepio/smb-glitchedworlds#6]
What I mean is:

1. Backport A+Start to start the game in hard mode from SMB2J glitch worlds hack, makes sense to have.
2. Add B+Start to start the game in 2 player mode. Maybe I want to take turns with Little Brother exploring these worlds. Maybe the glitch levels point to the address that contains the player and the level might change. Also, why not? 
                Currently, the only way to play 2 player is to hit the axe and press B to go back to the normal title menu, which doesn't allow glitch worlds.

4.  Press both A and B + START to do both of the above.

**Comment by threecreepio** [comment]
Sure, I added those, thanks!

**Comment by yum13241** [comment]
You're welcome.
